#!/usr/bin/env bash
#
# Remove an Abyssum install. Reverses what install.sh set up.
#
#   ./uninstall.sh                 # remove binaries + service + generated proxy config
#                                  # KEEP data (DB + config)
#   ./uninstall.sh --purge         # also remove data (/var/lib/abyssum, ~/.config/abyssum,
#                                  #   ~/.local/share/abyssum)
#   ./uninstall.sh --yes           # skip the confirmation prompt (for automation/testing)
#   curl -fsSL <raw>/uninstall.sh | bash -s -- --yes
#
# Safe by default: your database and config are preserved unless you pass --purge.
set -eu

PURGE=0
ASSUME_YES=0

USAGE="$(cat <<'EOF'
Usage: ./uninstall.sh [--purge] [--yes]
  --purge      also delete the database and config (data is kept by default)
  --yes, -y    do not prompt for confirmation
  -h, --help   show this help
EOF
)"

while [ $# -gt 0 ]; do
  case "$1" in
    --purge) PURGE=1; shift ;;
    --yes|-y) ASSUME_YES=1; shift ;;
    -h|--help) printf '%s\n' "$USAGE"; exit 0 ;;
    *) echo "uninstall.sh: unknown argument: $1" >&2; exit 2 ;;
  esac
done

SUDO=""
if [ "$(id -u)" -ne 0 ]; then SUDO="sudo"; fi

# Resolve the target user's home: under sudo, the invoking user's; otherwise $HOME
# (so a test can point it at a fixture with HOME).
if [ -n "${SUDO_USER:-}" ]; then
  RUN_HOME="$(getent passwd "$SUDO_USER" 2>/dev/null | cut -d: -f6)"
  [ -n "$RUN_HOME" ] || RUN_HOME="$HOME"
else
  RUN_HOME="$HOME"
fi

# Remove a path; use sudo only for paths outside the user's home.
del() {
  [ -e "$1" ] || return 0
  case "$1" in
    "${RUN_HOME}"/*) rm -rf "$1" ;;
    *) $SUDO rm -rf "$1" ;;
  esac
  echo "removed: $1"
}

echo "This will remove:"
echo "  - abyssum-web systemd service (if present)"
echo "  - abyssum / abyssum-web binaries from /usr/local/bin and ${RUN_HOME}/.local/bin"
echo "  - the abyssum-managed Caddy config (if generated by install.sh)"
if [ "$PURGE" -eq 1 ]; then
  echo "  - AND your data: /var/lib/abyssum, ${RUN_HOME}/.config/abyssum, ${RUN_HOME}/.local/share/abyssum"
else
  echo "  (data is kept — pass --purge to remove it too)"
fi

if [ "$ASSUME_YES" -ne 1 ]; then
  printf 'Proceed? [y/N] '
  read -r ans < /dev/tty || ans=""
  case "$ans" in [Yy]*) ;; *) echo "aborted."; exit 0 ;; esac
fi

# --- service (guard on the unit file so we never invoke sudo with nothing to do) ---
if [ -f /etc/systemd/system/abyssum-web.service ] && command -v systemctl >/dev/null 2>&1; then
  $SUDO systemctl disable --now abyssum-web >/dev/null 2>&1 || true
  del /etc/systemd/system/abyssum-web.service
  $SUDO systemctl daemon-reload || true
fi

# --- generated Caddy config (only what install.sh marked) ---
for cf in /etc/caddy/Caddyfile /etc/caddy/abyssum.caddyfile; do
  if [ -f "$cf" ] && grep -q 'abyssum-managed' "$cf" 2>/dev/null; then
    del "$cf"
    command -v systemctl >/dev/null 2>&1 && $SUDO systemctl reload caddy >/dev/null 2>&1 || true
  fi
done

# --- binaries ---
for d in /usr/local/bin "${RUN_HOME}/.local/bin"; do
  del "${d}/abyssum"
  del "${d}/abyssum-web"
done

# --- data (only with --purge) ---
if [ "$PURGE" -eq 1 ]; then
  del /var/lib/abyssum
  del "${RUN_HOME}/.config/abyssum"
  del "${RUN_HOME}/.local/share/abyssum"
fi

echo "uninstall.sh: done."
