#!/usr/bin/env bash
#
# Configure Caddy as a TLS reverse proxy in front of abyssum-web on a LAN / VPN.
#
# Topology: abyssum-web stays bound to 127.0.0.1:8000 (its default); Caddy faces
# the network on :443, terminates HTTPS with its own internal CA (a self-signed
# root — no public DNS or ACME needed), and reverse-proxies to abyssum-web. Only
# Caddy is exposed; the app itself is never on a routable interface.
#
# This generates a Caddyfile, validates it, and prints the run + trust steps. It
# does NOT install packages or start system services for you.
#
# Run with --help for usage.
set -euo pipefail

SITE=""
UPSTREAM_PORT="8000"
OUTFILE="./Caddyfile"
DO_TRUST=0
DO_RUN=0

USAGE="$(cat <<'EOF'
Usage:
  deploy/caddy-setup.sh [--site <host-or-ip>] [--port <n>] [--output <path>] [--trust] [--run]

Options:
  --site <host-or-ip>  hostname or IP clients will use (default: this host's primary IP)
  --port <n>           abyssum-web upstream port on 127.0.0.1 (default: 8000)
  --output <path>      where to write the Caddyfile (default: ./Caddyfile)
  --trust              run 'caddy trust' to install Caddy's internal root CA locally
  --run                exec 'caddy run' with the generated file (foreground; :443 needs root)
  -h, --help           show this help

Examples:
  deploy/caddy-setup.sh --site abyssum.lab        # generate ./Caddyfile for a hostname
  sudo deploy/caddy-setup.sh --run                # detect this box's IP and start Caddy now
EOF
)"

STEP="startup"
trap 'echo "caddy-setup.sh: failed during: ${STEP}" >&2' ERR

# --- parse args ---
while [ $# -gt 0 ]; do
  case "$1" in
    --site)   SITE="${2:?--site needs a value}"; shift 2 ;;
    --port)   UPSTREAM_PORT="${2:?--port needs a value}"; shift 2 ;;
    --output) OUTFILE="${2:?--output needs a value}"; shift 2 ;;
    --trust)  DO_TRUST=1; shift ;;
    --run)    DO_RUN=1; shift ;;
    -h|--help) printf '%s\n' "$USAGE"; exit 0 ;;
    *) echo "caddy-setup.sh: unknown argument: $1" >&2; exit 2 ;;
  esac
done

# --- require caddy (do not auto-install) ---
STEP="checking for caddy"
if ! command -v caddy >/dev/null 2>&1; then
  echo "caddy-setup.sh: 'caddy' not found on PATH." >&2
  echo "  Install it first: https://caddyserver.com/docs/install" >&2
  exit 1
fi

# --- resolve the site address ---
STEP="resolving site address"
if [ -z "$SITE" ]; then
  SITE="$(ip route get 1.1.1.1 2>/dev/null \
    | awk '{for (i=1;i<=NF;i++) if ($i=="src") { print $(i+1); exit }}')" || true
  if [ -z "$SITE" ]; then
    echo "caddy-setup.sh: could not autodetect an IP; pass --site <host-or-ip>." >&2
    exit 1
  fi
  echo "caddy-setup.sh: no --site given; using detected address ${SITE}"
fi

# --- write the Caddyfile ---
STEP="writing ${OUTFILE}"
cat > "$OUTFILE" <<EOF
# Generated by deploy/caddy-setup.sh — abyssum-web behind Caddy (internal TLS).
#
# abyssum-web stays on 127.0.0.1:${UPSTREAM_PORT}; only Caddy faces the network.
# 'tls internal' uses Caddy's own CA (a self-signed root) — trust it on each
# client, or run 'caddy trust' where clients connect from. See docs/deploy/CADDY.md.
https://${SITE} {
    reverse_proxy 127.0.0.1:${UPSTREAM_PORT}
    tls internal
    encode zstd gzip
    header -Server
    # abyssum-web already sets CSP, HSTS, X-Frame-Options, and nosniff itself.
}
EOF

# --- validate ---
STEP="validating ${OUTFILE}"
caddy validate --adapter caddyfile --config "$OUTFILE"
echo "caddy-setup.sh: wrote and validated ${OUTFILE}"

# --- optional: trust the internal CA ---
if [ "$DO_TRUST" -eq 1 ]; then
  STEP="installing Caddy internal CA (caddy trust)"
  caddy trust
fi

# --- optional: run in the foreground ---
if [ "$DO_RUN" -eq 1 ]; then
  STEP="running caddy"
  echo "caddy-setup.sh: starting caddy (Ctrl-C to stop)…"
  exec caddy run --adapter caddyfile --config "$OUTFILE"
fi

STEP="printing next steps"
cat <<EOF

Next steps
  1. Ensure abyssum-web is running on 127.0.0.1:${UPSTREAM_PORT} (its default).
  2. Run Caddy with this file (binding :443 needs root or the net_bind capability):
        sudo caddy run --config ${OUTFILE}
     …or install it under systemd (recommended for a persistent box):
        sudo cp ${OUTFILE} /etc/caddy/Caddyfile && sudo systemctl reload caddy
  3. Trust Caddy's internal CA so browsers don't warn:
        sudo caddy trust                      # on this host
     For other client machines, export the root CA and import it there —
     see docs/deploy/CADDY.md.
  4. Browse:  https://${SITE}/
EOF
